[package]
name = "token-vault-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-client = "0.26.0"
anchor-lang = "0.26.0"
anchor-spl = "0.26.0"
anyhow = "1.0"
shellexpand = "2.1"
solana-program = "1.14.11"
solana-sdk = "1.14.11"
tokio = { version = "1.23.0", features = ["full"] }
